{% set name = "bluesky-tiled-plugins" %}
{% set version = "2.0.0b55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bluesky_tiled_plugins-{{ version }}.tar.gz
  sha256: 3fd9aba7319b43a5628345da7428e76ba1b0895914811da4beb57fc87370c3f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - dask-core
    - mongoquery
    - pytz
    - tiled >=0.1.0b4
    - tzlocal

test:
  imports:
    - bluesky_tiled_plugins
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Tiled client plugins to provide an customized user experience for Bluesky data in Tiled
  home: http://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: For a user wishing to connect to a running Tiled server and access Bluesky data, this package, along with its dependency tiled[client], is all they need.
  doc_url: http://blueskyproject.io/databroker
  dev_url: https://github.com/bluesky/databroker/tree/main/bluesky-tiled-plugins

extra:
  recipe-maintainers:
    - nmaytan
    - danielballan
    - mrakitin
