{% set name = "bluesky-tiled-plugins" %}
{% set version = "2.0.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bluesky_tiled_plugins-{{ version }}.tar.gz
  sha256: 91e09b1a17aac932366d47f8856244048f6bed3fdf565639f53189b352ec43cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - dask-core
    - mongoquery
    - pytz
    - tiled-client >=0.2.0
    - tzlocal

test:
  imports:
    - bluesky_tiled_plugins
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Tiled client plugins to provide an customized user experience for Bluesky data in Tiled
  home: http://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: For a user wishing to connect to a running Tiled server and access Bluesky data, this package, along with its dependency tiled[client], is all they need.
  doc_url: http://blueskyproject.io/databroker
  dev_url: https://github.com/bluesky/databroker/tree/main/bluesky-tiled-plugins

extra:
  recipe-maintainers:
    - nmaytan
    - danielballan
    - mrakitin
