{% set name = "bluesky-tiled-plugins" %}
{% set version = "2.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/d3/74/09a8e31991eeb72d369142a7e02f8947ba182321e70b1cf9f8ca0de4289a/bluesky_tiled_plugins-{{ version }}.tar.gz
  sha256: 1a9acac4c40fa9d2740a1f1cdf63a98cc598a6208267a71b9ab428927403d24d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - dask-core
    - event-model
    - mongoquery
    - pytz
    - tiled-client >=0.2.0
    - tzlocal

test:
  imports:
    - bluesky_tiled_plugins
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Tiled client plugins to provide an customized user experience for Bluesky data in Tiled
  home: http://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: For a user wishing to connect to a running Tiled server and access Bluesky data, this package, along with its dependency tiled[client], is all they need.
  doc_url: http://blueskyproject.io/databroker
  dev_url: https://github.com/bluesky/databroker/tree/main/bluesky-tiled-plugins

extra:
  recipe-maintainers:
    - nmaytan
    - danielballan
    - mrakitin
